<?php

namespace Database\Seeders;

use App\Models\Compte;
use Illuminate\Database\Seeder;

/**
 * Plan comptable (base SYSCOHADA révisé, complétée de comptes propres à l'administration).
 * Adaptez-le au plan comptable de l'État (PCE) en vigueur si nécessaire.
 * Vous pouvez ajouter vos sous-comptes depuis Paramètres › Plan comptable.
 */
class PlanComptableSeeder extends Seeder
{
    public function run(): void
    {
        foreach (self::comptes() as $numero => $libelle) {
            Compte::updateOrCreate(['numero' => (string) $numero], ['libelle' => $libelle, 'actif' => true]);
        }
    }

    public static function comptes(): array
    {
        return [
            // CLASSE 1 - COMPTES DE RESSOURCES DURABLES
            '10' => 'Capital',
            '101' => 'Capital social',
            '1011' => 'Capital souscrit, non appelé',
            '1012' => 'Capital souscrit, appelé, non versé',
            '1013' => 'Capital souscrit, appelé, versé, non amorti',
            '103' => 'Capital personnel',
            '104' => "Compte de l'exploitant",
            '105' => 'Primes liées au capital social',
            '106' => 'Écarts de réévaluation',
            '109' => 'Apporteurs, capital souscrit, non appelé',
            '11' => 'Réserves',
            '111' => 'Réserve légale',
            '112' => 'Réserves statutaires ou contractuelles',
            '113' => 'Réserves réglementées',
            '118' => 'Autres réserves',
            '12' => 'Report à nouveau',
            '121' => 'Report à nouveau créditeur',
            '129' => 'Report à nouveau débiteur',
            '13' => "Résultat net de l'exercice",
            '131' => 'Résultat net : bénéfice',
            '139' => 'Résultat net : perte',
            '14' => "Subventions d'investissement",
            '141' => "Subventions d'équipement",
            '15' => 'Provisions réglementées et fonds assimilés',
            '16' => 'Emprunts et dettes assimilées',
            '161' => 'Emprunts obligataires',
            '162' => 'Emprunts et dettes auprès des établissements de crédit',
            '165' => 'Dépôts et cautionnements reçus',
            '166' => 'Intérêts courus',
            '168' => 'Autres emprunts et dettes',
            '17' => 'Dettes de location-acquisition',
            '18' => 'Dettes liées à des participations et comptes de liaison',
            '19' => 'Provisions pour risques et charges',
            '191' => 'Provisions pour litiges',

            // CLASSE 2 - COMPTES D'ACTIF IMMOBILISÉ
            '21' => 'Immobilisations incorporelles',
            '211' => 'Frais de développement',
            '212' => 'Brevets, licences, concessions et droits similaires',
            '213' => 'Logiciels et sites internet',
            '215' => 'Fonds commercial',
            '22' => 'Terrains',
            '222' => 'Terrains nus',
            '223' => 'Terrains bâtis',
            '23' => 'Bâtiments, installations techniques et agencements',
            '231' => 'Bâtiments sur sol propre',
            '234' => 'Aménagements, agencements et installations techniques',
            '235' => 'Aménagements de bureaux',
            '24' => 'Matériel, mobilier et actifs biologiques',
            '241' => 'Matériel et outillage industriel et commercial',
            '244' => 'Matériel et mobilier',
            '2441' => 'Matériel de bureau',
            '2442' => 'Matériel informatique',
            '2444' => 'Mobilier de bureau',
            '245' => 'Matériel de transport',
            '25' => 'Avances et acomptes versés sur immobilisations',
            '26' => 'Titres de participation',
            '27' => 'Autres immobilisations financières',
            '275' => 'Dépôts et cautionnements versés',
            '28' => 'Amortissements',
            '281' => 'Amortissements des immobilisations incorporelles',
            '283' => 'Amortissements des bâtiments et installations',
            '284' => 'Amortissements du matériel',
            '29' => 'Dépréciations des immobilisations',

            // CLASSE 3 - COMPTES DE STOCKS
            '31' => 'Marchandises',
            '311' => 'Marchandises',
            '32' => 'Matières premières et fournitures liées',
            '33' => 'Autres approvisionnements',
            '34' => 'Produits en cours',
            '35' => 'Services en cours',
            '36' => 'Produits finis',
            '37' => 'Produits intermédiaires et résiduels',
            '38' => 'Stocks en cours de route, en consignation ou en dépôt',
            '39' => 'Dépréciations des stocks',

            // CLASSE 4 - COMPTES DE TIERS
            '40' => 'Fournisseurs et comptes rattachés',
            '401' => 'Fournisseurs, dettes en compte',
            '4011' => 'Fournisseurs et prestataires',
            '402' => 'Fournisseurs, effets à payer',
            '404' => "Fournisseurs, acquisitions courantes d'immobilisations",
            '408' => 'Fournisseurs, factures non parvenues',
            '409' => 'Fournisseurs débiteurs',
            '41' => 'Clients et comptes rattachés',
            '411' => 'Redevables et usagers',
            '4111' => 'Redevables',
            '412' => 'Clients, effets à recevoir',
            '416' => 'Créances clients litigieuses ou douteuses',
            '418' => 'Clients, produits à recevoir',
            '419' => 'Clients créditeurs',
            '42' => 'Personnel',
            '421' => 'Personnel, avances et acomptes',
            '422' => 'Personnel, rémunérations dues',
            '428' => 'Personnel, charges à payer',
            '43' => 'Organismes sociaux',
            '431' => 'Sécurité sociale',
            '432' => 'Caisses de retraite',
            '44' => 'État et collectivités publiques',
            '441' => 'État, impôt sur les bénéfices',
            '442' => 'État, autres impôts et taxes',
            '443' => 'État, TVA facturée',
            '4431' => 'TVA facturée sur ventes',
            '4432' => 'TVA facturée sur prestations de services',
            '444' => 'État, TVA due ou crédit de TVA',
            '4441' => 'État, TVA due',
            '4449' => 'État, crédit de TVA à reporter',
            '445' => 'État, TVA récupérable',
            '4451' => 'TVA récupérable sur immobilisations',
            '4452' => 'TVA récupérable sur achats',
            '4453' => 'TVA récupérable sur transport',
            '4454' => 'TVA récupérable sur services extérieurs et autres charges',
            '447' => 'État, impôts retenus à la source',
            '449' => 'État, créances et dettes diverses',
            '45' => 'Organismes internationaux',
            '46' => 'Apporteurs, associés et groupe',
            '461' => 'Apporteurs, opérations sur le capital',
            '462' => 'Associés, comptes courants',
            '465' => 'Associés, dividendes à payer',
            '47' => 'Débiteurs et créditeurs divers',
            '471' => 'Débiteurs et créditeurs divers',
            '476' => "Charges constatées d'avance",
            '477' => "Produits constatés d'avance",
            '48' => 'Créances et dettes hors activités ordinaires',
            '481' => "Fournisseurs d'investissements",
            '485' => "Créances sur cessions d'immobilisations",
            '49' => 'Dépréciations et provisions pour risques à court terme (tiers)',
            '491' => 'Dépréciations des comptes clients',

            // CLASSE 5 - COMPTES DE TRÉSORERIE
            '50' => 'Titres de placement',
            '51' => 'Valeurs à encaisser',
            '511' => 'Effets à encaisser',
            '513' => 'Chèques à encaisser',
            '52' => 'Banques',
            '521' => 'Banques locales',
            '53' => 'Établissements financiers et assimilés',
            '531' => 'Chèques postaux',
            '532' => 'Trésor public (compte de dépôt)',
            '55' => 'Instruments de monnaie électronique',
            '552' => 'Monnaie électronique - téléphone portable',
            '56' => "Banques, crédits de trésorerie et d'escompte",
            '561' => 'Crédits de trésorerie',
            '565' => 'Escompte de crédits ordinaires',
            '57' => 'Caisse',
            '571' => 'Caisse siège social',
            '572' => 'Caisse succursale',
            '58' => "Régies d'avances, accréditifs et virements internes",
            '581' => "Régies d'avance",
            '585' => 'Virements de fonds',
            '59' => 'Dépréciations et provisions pour risques à court terme (trésorerie)',

            // CLASSE 6 - COMPTES DE CHARGES DES ACTIVITÉS ORDINAIRES
            '60' => 'Achats et variations de stocks',
            '601' => 'Achats de marchandises',
            '602' => 'Achats de matières premières et fournitures liées',
            '603' => 'Variations des stocks de biens achetés',
            '604' => 'Achats stockés de matières et fournitures consommables',
            '605' => 'Autres achats',
            '6051' => 'Fournitures non stockables - Eau',
            '6052' => 'Fournitures non stockables - Électricité',
            '6053' => 'Fournitures non stockables - Autres énergies',
            '6054' => "Fournitures d'entretien non stockables",
            '6055' => 'Fournitures de bureau non stockables',
            '6056' => 'Achats de petit matériel et outillage',
            '608' => "Achats d'emballages",
            '61' => 'Transports',
            '612' => 'Transports sur ventes',
            '614' => 'Transports du personnel',
            '616' => 'Transports de plis',
            '618' => 'Autres frais de transport',
            '62' => 'Services extérieurs',
            '621' => 'Sous-traitance générale',
            '622' => 'Locations et charges locatives',
            '624' => 'Entretien, réparations, remise en état et maintenance',
            '625' => "Primes d'assurance",
            '626' => 'Études, recherches et documentation',
            '627' => 'Publicité, publications, relations publiques',
            '628' => 'Frais de télécommunications',
            '63' => 'Autres services extérieurs',
            '631' => 'Frais bancaires',
            '632' => "Rémunérations d'intermédiaires et de conseils",
            '633' => 'Frais de formation du personnel',
            '637' => "Rémunérations de personnel extérieur à l'entité",
            '638' => 'Autres charges externes',
            '6381' => 'Frais de mission et de déplacement',
            '64' => 'Impôts et taxes',
            '641' => 'Impôts et taxes directs',
            '645' => 'Impôts et taxes indirects',
            '646' => "Droits d'enregistrement",
            '647' => 'Pénalités, amendes fiscales',
            '648' => 'Autres impôts et taxes',
            '65' => 'Autres charges',
            '651' => 'Pertes sur créances clients et autres débiteurs',
            '658' => 'Charges diverses',
            '6581' => 'Transferts courants aux établissements publics',
            '6582' => 'Transferts courants aux collectivités territoriales',
            '6583' => 'Bourses, secours et aides sociales',
            '6585' => "Subventions d'investissement versées (transferts en capital)",
            '66' => 'Charges de personnel',
            '661' => 'Rémunérations directes versées au personnel national',
            '663' => 'Indemnités forfaitaires versées au personnel',
            '664' => 'Charges sociales',
            '668' => 'Autres charges sociales',
            '67' => 'Frais financiers et charges assimilées',
            '671' => 'Intérêts des emprunts',
            '674' => 'Autres intérêts',
            '676' => 'Pertes de change',
            '68' => 'Dotations aux amortissements',
            '681' => "Dotations aux amortissements d'exploitation",
            '69' => 'Dotations aux provisions et aux dépréciations',
            '691' => "Dotations aux provisions et dépréciations d'exploitation",
            '697' => 'Dotations aux provisions et dépréciations financières',

            // CLASSE 7 - COMPTES DE PRODUITS DES ACTIVITÉS ORDINAIRES
            '70' => 'Ventes',
            '701' => 'Ventes de marchandises',
            '702' => 'Ventes de produits finis',
            '703' => 'Ventes de produits intermédiaires',
            '704' => 'Ventes de produits résiduels',
            '705' => 'Travaux facturés',
            '706' => 'Services vendus',
            '707' => 'Produits accessoires',
            '7064' => 'Redevances et droits administratifs',
            '7065' => "Frais de concours et d'inscription",
            '71' => "Subventions d'exploitation",
            '711' => 'Dons et subventions reçus',
            '72' => 'Production immobilisée',
            '73' => 'Variations des stocks de biens et de services produits',
            '75' => 'Autres produits',
            '758' => 'Produits divers',
            '7581' => 'Produits domaniaux et loyers perçus',
            '77' => 'Revenus financiers et produits assimilés',
            '771' => 'Intérêts de prêts et créances diverses',
            '776' => 'Gains de change',
            '78' => 'Transferts de charges',
            '781' => "Transferts de charges d'exploitation",
            '79' => 'Reprises de provisions, de dépréciations et autres',
            '791' => "Reprises de provisions et dépréciations d'exploitation",

            // CLASSE 8 - AUTRES CHARGES ET AUTRES PRODUITS
            '81' => "Valeurs comptables des cessions d'immobilisations",
            '82' => "Produits des cessions d'immobilisations",
            '83' => 'Charges hors activités ordinaires',
            '84' => 'Produits hors activités ordinaires',
            '85' => 'Dotations hors activités ordinaires',
            '86' => 'Reprises hors activités ordinaires',
            '87' => 'Participation des travailleurs',
            '88' => "Subventions d'équilibre",
            '89' => 'Impôts sur le résultat',
            '891' => "Impôts sur les bénéfices de l'exercice",
        ];
    }
}
